# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20161024_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image01',
            field=models.ImageField(blank=True, default='01.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image02',
            field=models.ImageField(blank=True, default='02.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image03',
            field=models.ImageField(blank=True, default='03.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image04',
            field=models.ImageField(blank=True, default='04.jpg', null=True, upload_to='images/'),
        ),
    ]
